### ISSUE TITLE
请问request自定义请求参数绑定未生效是bug吗？

### ISSUE THREAD

**Issue by learning-go123** [gotomicro/ego-gen-api#49]
这两个函数没有生成参数，请问是这样写吗？
配置：
```
  request:
    - type: '*gin/core.Context'
      method: 'DefaultQuery' # gin提供的函数
      return:
        data:
          type: 'args[0]'
    - type: '*gin/core.Context'
      method: 'MyQuery' # 自定义函数
      return:
        data:
          type: 'args[0]'
```
go代码：
```go
	current := c.Query("current")
	pageSize := c.Query("pageSize")
	fmt.Println("xxx", current, pageSize)

	test := c.MyQuery("test")
	fmt.Println("test", test)

	test2 := c.DefaultQuery("test22", "222")
	fmt.Println("test", test2)
```
生成的openapi
<img width="414" alt="image" src="https://user-images.githubusercontent.com/88469563/215668958-bf4388c4-ca52-43c8-a653-99398749c702.png">

**Comment by link-duan** [comment]
暂时只支持自定义 Bind 方法。像 Query()、Param() 方法这种暂不支持自定义，只能调用 gin 内置的方法。

对于 gin 内置的 DefaultQuery() 方法暂未支持，后续我这边会进行支持。也欢迎提交 PR 一起完善。

**Comment by learning-go123** [comment]
@link-duan 大佬c.BindUri能帮忙支持下吗


现在有个问题这种uri： /api/rule/{id}  id用Param拿出来是string，但是list结构是int。导致生成出来的类型会不一样 
如图：
<img width="418" alt="image" src="https://user-images.githubusercontent.com/88469563/215729049-ed2f5963-6ed5-4ab0-9fd0-04de885f6113.png">


还有个问题就是认证，这个现在有支持吗？
部分接口需要认证才能访问。期望能支持块注释
在yaml写了下面的配置貌似也没用
<img width="272" alt="image" src="https://user-images.githubusercontent.com/88469563/215723154-2adab0c4-56a1-4cb5-bf61-df2347add56f.png">

**Comment by link-duan** [comment]
c.BindUri() 和 权限 功能都是很好的建议，我这边会尽快支持下。

> @link-duan 大佬c.BindUri能帮忙支持下吗
> 
> 现在有个问题这种uri： /api/rule/{id} id用Param拿出来是string，但是list结构是int。导致生成出来的类型会不一样 如图： <img alt="image" width="418" src="https://user-images.githubusercontent.com/88469563/215729049-ed2f5963-6ed5-4ab0-9fd0-04de885f6113.png">
> 
> 还有个问题就是认证，这个现在有支持吗？ 部分接口需要认证才能访问。期望能支持块注释 在yaml写了下面的配置貌似也没用 <img alt="image" width="272" src="https://user-images.githubusercontent.com/88469563/215723154-2adab0c4-56a1-4cb5-bf61-df2347add56f.png">

**Comment by link-duan** [comment]
`c.DefaultQuery()`，`c.DefaultPostForm()` 已支持 #50 ，请升级新版本后使用

**Comment by learning-go123** [comment]
@link-duan 能否简单的实现下这个request自定义函数，因为的有的取c.Param的方法可能被不在当前扫描的方法里被封装在其他方法里
例如：扫描到有这个MyQuery个函数，不需要扫描的里面的类型，直接把properties的数据塞进去呢,这样我直接用方法名去区别

```yaml
properties:
  request:
    - type: '*gin/core.Context'
      method: 'MyQuery' # 自定义函数
      return:
        data:
          type: 'object'
          properties:
            page:
              type: 'number'
            pageSize:
              type: 'number'
```
